name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push the Docker image
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASS: ${{ secrets.DOCKER_PASS }}
      run: | 
        docker login -u $DOCKER_USER -p $DOCKER_PASS
        cd ZalandoCoupon.Application
        docker build -t rodeknopje/zalando-coupon .
        docker push rodeknopje/zalando-coupon
